/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jefferson
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        //Añadiendo los Manejadores a los botones
        btnBuscarEst.addActionListener(new manejadorBuscarEstudiante());
        btnBuscarPro.addActionListener(new manejadorBuscarProfesor());
        btnBuscarCur.addActionListener(new manejadorBuscarCurso());
        btnRegistrarEst.addActionListener(new manejadorRegistrarEstudiante());
        btnRegistrarPro.addActionListener(new manejadorRegistrarProfesor());
        btnRegistrarCur.addActionListener(new manejadorRegistrarCurso());
        btnAñadirAsist.addActionListener(new manejadorAsistencia());
        btnSemestres.addActionListener(new manejadorSemestres());
        btnProgramas.addActionListener(new manejadorProgramas());
        btnClase.addActionListener(new manejadorClase());
        btnRegistrarProgram.addActionListener(new manejadorRegPrograma());
        btnRegSem.addActionListener(new manejadorRegSem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnBuscar = new javax.swing.JMenu();
        btnBuscarEst = new javax.swing.JMenuItem();
        btnBuscarPro = new javax.swing.JMenuItem();
        btnBuscarCur = new javax.swing.JMenuItem();
        btnRegistrar = new javax.swing.JMenu();
        btnRegistrarEst = new javax.swing.JMenuItem();
        btnRegistrarPro = new javax.swing.JMenuItem();
        btnRegistrarCur = new javax.swing.JMenuItem();
        btnClase = new javax.swing.JMenuItem();
        btnRegistrarProgram = new javax.swing.JMenuItem();
        btnRegSem = new javax.swing.JMenuItem();
        btnAsistencia = new javax.swing.JMenu();
        btnAñadirAsist = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnSemestres = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnProgramas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        btnBuscar.setText("Buscar");

        btnBuscarEst.setText("Buscar Estudiante");
        btnBuscar.add(btnBuscarEst);

        btnBuscarPro.setText("Buscar Profesor");
        btnBuscar.add(btnBuscarPro);

        btnBuscarCur.setText("Buscar Curso");
        btnBuscar.add(btnBuscarCur);

        jMenuBar1.add(btnBuscar);

        btnRegistrar.setText("Registrar");

        btnRegistrarEst.setText("Registrar Estudiante");
        btnRegistrar.add(btnRegistrarEst);

        btnRegistrarPro.setText("Registrar Profesor");
        btnRegistrar.add(btnRegistrarPro);

        btnRegistrarCur.setText("Registrar Curso");
        btnRegistrar.add(btnRegistrarCur);

        btnClase.setText("Registrar Clase");
        btnRegistrar.add(btnClase);

        btnRegistrarProgram.setText("Registrar Programa");
        btnRegistrar.add(btnRegistrarProgram);

        btnRegSem.setText("Registrar Semestre");
        btnRegistrar.add(btnRegSem);

        jMenuBar1.add(btnRegistrar);

        btnAsistencia.setText("Asistencia");

        btnAñadirAsist.setText("Añadir Asistencia");
        btnAsistencia.add(btnAñadirAsist);

        jMenuBar1.add(btnAsistencia);

        jMenu1.setText("Semestres");

        btnSemestres.setText("Mostrar Semestres");
        jMenu1.add(btnSemestres);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Programas");

        btnProgramas.setText("Mostrar Programas");
        jMenu2.add(btnProgramas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAsistencia;
    private javax.swing.JMenuItem btnAñadirAsist;
    private javax.swing.JMenu btnBuscar;
    private javax.swing.JMenuItem btnBuscarCur;
    private javax.swing.JMenuItem btnBuscarEst;
    private javax.swing.JMenuItem btnBuscarPro;
    private javax.swing.JMenuItem btnClase;
    private javax.swing.JMenuItem btnProgramas;
    private javax.swing.JMenuItem btnRegSem;
    private javax.swing.JMenu btnRegistrar;
    private javax.swing.JMenuItem btnRegistrarCur;
    private javax.swing.JMenuItem btnRegistrarEst;
    private javax.swing.JMenuItem btnRegistrarPro;
    private javax.swing.JMenuItem btnRegistrarProgram;
    private javax.swing.JMenuItem btnSemestres;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    //Manejadores
    //Manejador Buscar Estudiante
    public class manejadorBuscarEstudiante implements ActionListener {

        private buscarEstudianteGUI buscarEstUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (buscarEstUI == null) {
                this.buscarEstUI = new buscarEstudianteGUI();
                escritorio.add(buscarEstUI);
            }
            buscarEstUI.setVisible(true);
        }
    }

    //Manejador Buscar Profesor
    public class manejadorBuscarProfesor implements ActionListener {

        private buscarProfesorGUI buscarProUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (buscarProUI == null) {
                this.buscarProUI = new buscarProfesorGUI();
                escritorio.add(buscarProUI);
            }
            buscarProUI.setVisible(true);
        }
    }

    //Manejador Buscar Curso
    public class manejadorBuscarCurso implements ActionListener {

        private buscarCursoGUI buscarCurUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (buscarCurUI == null) {
                this.buscarCurUI = new buscarCursoGUI();
                escritorio.add(buscarCurUI);
            }
            buscarCurUI.setVisible(true);
        }
    }

    //Manejador Registrar Estudiante
    public class manejadorRegistrarEstudiante implements ActionListener {

        private registrarEstudianteGUI registrarEstUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (registrarEstUI == null) {
                this.registrarEstUI = new registrarEstudianteGUI();
                escritorio.add(registrarEstUI);
            }
            registrarEstUI.setVisible(true);
        }
    }

    //Manejador Registrar Profesor
    public class manejadorRegistrarProfesor implements ActionListener {

        private registrarProfesorGUI registrarProUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (registrarProUI == null) {
                this.registrarProUI = new registrarProfesorGUI();
                escritorio.add(registrarProUI);
            }
            registrarProUI.setVisible(true);
        }
    }

    //Manejador Registrar Curso
    public class manejadorRegistrarCurso implements ActionListener {

        private registrarCursoGUI registrarCurUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (registrarCurUI == null) {
                this.registrarCurUI = new registrarCursoGUI();
                escritorio.add(registrarCurUI);
            }
            registrarCurUI.setVisible(true);
        }
    }


    //Manejador Asistencia
    public class manejadorAsistencia implements ActionListener {

        private asistenciaGUI asistenciaUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (asistenciaUI == null) {
                this.asistenciaUI = new asistenciaGUI();
                escritorio.add(asistenciaUI);
            }
            asistenciaUI.setVisible(true);
        }
    }
    
        //Manejador Mostrar Semestres
    public class manejadorSemestres implements ActionListener {

        private mostrarSemestres semestresUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (semestresUI == null) {
                this.semestresUI = new mostrarSemestres();
                escritorio.add(semestresUI);
            }
            semestresUI.setVisible(true);
        }
    }
    
    //Manejador mostrar programas
    public class manejadorProgramas implements ActionListener {

        private mostrarProgramas programasUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (programasUI == null) {
                this.programasUI = new mostrarProgramas();
                escritorio.add(programasUI);
            }
            programasUI.setVisible(true);
        }
    }
    
    //Manejador mostrar Clase
    public class manejadorClase implements ActionListener {

        private registrarClase claseUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (claseUI == null) {
                this.claseUI = new registrarClase();
                escritorio.add(claseUI);
            }
            claseUI.setVisible(true);
        }
    }
    
    //Manejador Registrar Programa
    public class manejadorRegPrograma implements ActionListener {

        private registrarProgramas programasUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (programasUI == null) {
                this.programasUI = new registrarProgramas();
                escritorio.add(programasUI);
            }
            programasUI.setVisible(true);
        }
    }
    
    //Manejador Registrar Semestre
    public class manejadorRegSem implements ActionListener {

        private registrarSemestre semestreUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (semestreUI == null) {
                this.semestreUI = new registrarSemestre();
                escritorio.add(semestreUI);
            }
            semestreUI.setVisible(true);
        }
    }
}
